sudo: required
dist: trusty
language: generic
compiler:
  - gcc

branches:
  only:
    - master
    - develop

install:
  - sudo sh -c 'echo "deb http://packages.dink.org/dink/ubuntu trusty main" > /etc/apt/sources.list.d/dink-latest.list'
  - wget http://packages.dink.org/dink.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-catkin-pkg python-rosdep ros-indigo-catkin -qq
  - sudo rosdep init
  - rosdep update 
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/package
  - cd /tmp/ws
  - rosdep install --from-paths src --ignore-src --rosdistro indigo -y

script:
  - source /opt/ros/indigo/setup.bash
  - catkin_make
  - catkin_make install
