sudo: required
dist: trusty
language: generic
services:
  - docker
compiler:
  - gcc

notifications:
  email:
    on_failure: always

env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=dink DOCKER_BASE_IMAGE=dink:indigo-dink-core
    - ROS_DISTRO="kinetic" ROS_REPO=dink DOCKER_BASE_IMAGE=dink:kinetic-dink-core
    - ROS_DISTRO="kinetic" ROS_REPO=dink-shadow-fixed DOCKER_BASE_IMAGE=dink:kinetic-dink-core
    - ROS_DISTRO="lunar" ROS_REPO=dink DOCKER_BASE_IMAGE=dink:lunar-dink-core
    - ROS_DISTRO="lunar" ROS_REPO=dink-shadow-fixed DOCKER_BASE_IMAGE=dink:lunar-dink-core
    - ROS_DISTRO="melodic" ROS_REPO=dink DOCKER_BASE_IMAGE=dink:melodic-dink-core
    - ROS_DISTRO="melodic" ROS_REPO=dink-shadow-fixed DOCKER_BASE_IMAGE=dink:melodic-dink-core

matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" ROS_REPO=dink-shadow-fixed DOCKER_BASE_IMAGE=dink:kinetic-dink-core
    - env: ROS_DISTRO="lunar" ROS_REPO=dink-shadow-fixed DOCKER_BASE_IMAGE=dink:lunar-dink-core
    - env: ROS_DISTRO="melodic" ROS_REPO=dink-shadow-fixed DOCKER_BASE_IMAGE=dink:melodic-dink-core

install:
  git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  source .ci_config/travis.sh
